#%RAML 1.0
title: PAPI Student Counselling

uses:
  commons: /exchange_modules/26105a91-12e5-4470-b3a0-40b228e3e2a0/sc_commonslib/0.0.6/sc_commonslib.raml

types:
  enrolled_type: commons.enrolment_type

/enroller:
  is: 
    - commons.client_id_required
            
  post:
    description: Enrollment Proccess
    body:
      application/json:
        example: !include /examples/StudentRequest.json
        
    responses:
      201:
        description: Enrolment successful
        body:
          application/json:
            example: !include /examples/EnrolmentSuccess.json
      
      404:
        description: Student not found
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Requested student id not found"}
      
      409:
        description: Enrolment already exists
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Student already enrolled"}

      412:
        description: Enrolment failed for non matching conditions
        body:
          application/json:
            type: commons.error_response
            examples: 
              criteriaFail: {"error_message": "Criteria for requested colleges too high"}
              seatsFail: {"error_message": "No available seats in requested colleges"}

      500:
        description: Internal enrolment error
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Student enrolment failed"}

/ping:
  get:
    description: Healthcheck endpoint
    responses:
      200:
        description: Healthcheck service online
        body:
          application/json:
            example: !include /examples/Healthcheck.json
        
       